#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
umask 077

[[ ${EUID:-$(id -u)} -eq 0 ]] || {
  echo "ERROR: run with sudo: sudo bash tools/runner/install-rpi5-audit-dispatcher.sh" >&2
  exit 1
}

for user in github-runner andris; do
  id "$user" >/dev/null 2>&1 || {
    echo "ERROR: required local user is missing: $user" >&2
    exit 1
  }
done

for command in git install python3 runuser sha256sum stat systemctl visudo; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "ERROR: required command is missing: $command" >&2
    exit 1
  }
done

RUNNER_SERVICE="actions.runner.rozkalnsandris-hermes-deals.rpi5-hermes-deals-audit.service"
DISPATCHER="/usr/local/sbin/hermes-deals-audit-dispatch"
REGISTER="/usr/local/sbin/hermes-deals-audit-register"
SUDOERS="/etc/sudoers.d/hermes-deals-audit-runner"
REGISTRY_DIR="/etc/hermes-deals-audits.d"
LIBEXEC_DIR="/usr/local/libexec/hermes-deals-audits"
STAGING_ROOT="/home/andris/hermes-deals-runner-evidence"

TMPDIR_INSTALL="$(mktemp -d /tmp/hermes-deals-audit-installer.XXXXXX)"
cleanup() {
  rm -rf -- "$TMPDIR_INSTALL"
}
trap cleanup EXIT

cat > "$TMPDIR_INSTALL/hermes-deals-audit-dispatch" <<'DISPATCH'
#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
umask 077
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PATH

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

[[ ${EUID:-$(id -u)} -eq 0 ]] || fail "dispatcher must run as root through sudo"
[[ $# -eq 3 ]] || fail "usage: hermes-deals-audit-dispatch <audit> <registered-commit-sha> <artifact-dir>"

AUDIT="$1"
EXPECTED_SHA="$2"
EXPORT_DIR="$3"
REGISTRY_DIR='/etc/hermes-deals-audits.d'
STAGING_ROOT='/home/andris/hermes-deals-runner-evidence'

[[ "$AUDIT" =~ ^[a-z0-9][a-z0-9-]{0,63}$ ]] || fail "invalid audit name"
[[ "$EXPECTED_SHA" =~ ^[0-9a-f]{40}$ ]] || fail "invalid commit SHA"

EXPORT_DIR="$(readlink -f -- "$EXPORT_DIR")"
[[ -d "$EXPORT_DIR" ]] || fail "artifact directory does not exist"
[[ "$EXPORT_DIR" == /home/github-runner/_work/_temp/hermes-deals-audit-* ]] || fail "artifact directory is outside the runner temp allowlist"
[[ "$(stat -c '%U' "$EXPORT_DIR")" == 'github-runner' ]] || fail "artifact directory is not owned by github-runner"
[[ "$(stat -c '%a' "$EXPORT_DIR")" == '700' ]] || fail "artifact directory permissions must be 0700"

RUN_KEY="$(basename -- "$EXPORT_DIR")"
[[ "$RUN_KEY" =~ ^hermes-deals-audit-[0-9]+-[0-9]+$ ]] || fail "unexpected runner artifact directory name"
STAGING_DIR="$STAGING_ROOT/$RUN_KEY"

install -d -o andris -g andris -m 0700 "$STAGING_ROOT"
[[ ! -e "$STAGING_DIR" ]] || fail "staging directory already exists"
install -d -o andris -g andris -m 0700 "$STAGING_DIR"

cleanup() {
  rm -rf -- "$STAGING_DIR"
}
trap cleanup EXIT

AUDIT_RC=1
case "$AUDIT" in
  runner-smoke)
    runuser -u andris -- /usr/bin/env -i \
      HOME=/home/andris \
      USER=andris \
      LOGNAME=andris \
      PATH=/usr/local/bin:/usr/bin:/bin \
      LANG=C.UTF-8 \
      AUDIT_SHA="$EXPECTED_SHA" \
      AUDIT_OUT="$STAGING_DIR/runner-smoke.json" \
      /usr/bin/python3 - <<'PY'
import json
import os
import pathlib
import platform
import socket

out = pathlib.Path(os.environ["AUDIT_OUT"])
out.write_text(
    json.dumps(
        {
            "audit": "runner-smoke",
            "commit_sha": os.environ["AUDIT_SHA"],
            "hostname": socket.gethostname(),
            "machine": platform.machine(),
            "production_apply_authorized": False,
            "runner_to_dispatcher_contract": True,
        },
        indent=2,
        sort_keys=True,
    )
    + "\n",
    encoding="utf-8",
)
PY
    AUDIT_RC=0
    ;;

  b15m2-v08)
    CONF="$REGISTRY_DIR/$AUDIT.conf"
    [[ -f "$CONF" && ! -L "$CONF" ]] || fail "audit is not registered: $AUDIT"
    [[ "$(stat -c '%U:%G' "$CONF")" == 'root:root' ]] || fail "audit registry ownership is invalid"
    [[ "$(stat -c '%a' "$CONF")" =~ ^(600|640|644)$ ]] || fail "audit registry permissions are invalid"

    # The registry file is root-owned, generated by the root-only register tool,
    # and contains only previously validated fixed-format values.
    # shellcheck disable=SC1090
    source "$CONF"

    [[ "${audit_name:-}" == "$AUDIT" ]] || fail "audit registry name mismatch"
    [[ "${commit_sha:-}" == "$EXPECTED_SHA" ]] || fail "requested commit is not the registered audit commit"
    [[ "${script_sha256:-}" =~ ^[0-9a-f]{64}$ ]] || fail "registered script SHA is invalid"
    [[ "${script_path:-}" == "/usr/local/libexec/hermes-deals-audits/$AUDIT.sh" ]] || fail "registered script path is invalid"
    [[ -f "$script_path" && ! -L "$script_path" ]] || fail "registered audit script is missing or unsafe"
    [[ "$(stat -c '%U:%G' "$script_path")" == 'root:root' ]] || fail "registered script ownership is invalid"
    [[ "$(sha256sum "$script_path" | awk '{print $1}')" == "$script_sha256" ]] || fail "registered script content drift"

    set +e
    runuser -u andris -- /usr/bin/env -i \
      HOME=/home/andris \
      USER=andris \
      LOGNAME=andris \
      SHELL=/bin/bash \
      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
      LANG=C.UTF-8 \
      HERMES_AUDIT_TRIGGER=github-actions \
      HERMES_AUDIT_EXPECTED_BRANCH=main \
      HERMES_AUDIT_EXPECTED_HEAD="$EXPECTED_SHA" \
      HERMES_AUDIT_EXPORT_DIR="$STAGING_DIR" \
      /bin/bash --noprofile --norc "$script_path" \
      > "$STAGING_DIR/audit-execution.log" 2>&1
    AUDIT_RC=$?
    set -e
    ;;

  *)
    fail "audit is not allowlisted: $AUDIT"
    ;;
esac

python3 - "$STAGING_DIR" "$EXPORT_DIR/audit-evidence" "$AUDIT" "$EXPECTED_SHA" "$AUDIT_RC" <<'PY'
import hashlib
import json
import os
import pathlib
import re
import shutil
import stat
import sys
import tarfile

source = pathlib.Path(sys.argv[1])
destination = pathlib.Path(sys.argv[2])
audit = sys.argv[3]
commit_sha = sys.argv[4]
audit_rc = int(sys.argv[5])

if not source.is_dir():
    raise SystemExit("staging evidence directory is missing")

sensitive_name = re.compile(
    r"(?:^|/)(?:\.env(?:\..*)?|production\.dump|admin\.password|runtime\.password|migrator\.password|bad\.password|[^/]+\.(?:pgpass|pem|key))$",
    re.IGNORECASE,
)
sensitive_content = re.compile(
    rb"(?:-----BEGIN [A-Z ]*PRIVATE KEY-----|(?:ghp|gho|ghu|ghs|github_pat)_[A-Za-z0-9_]{20,}|PGPASSWORD=|--token[ =]|postgresql(?:\+[^:]+)?://[^\s:/]+:[^\s@]+@)",
    re.IGNORECASE,
)

files = []
total_bytes = 0
for path in sorted(source.rglob("*")):
    relative = path.relative_to(source)
    info = path.lstat()
    if stat.S_ISLNK(info.st_mode) or not (stat.S_ISDIR(info.st_mode) or stat.S_ISREG(info.st_mode)):
        raise SystemExit(f"unsafe evidence member type: {relative}")
    if sensitive_name.search(relative.as_posix()):
        raise SystemExit(f"sensitive evidence filename rejected: {relative}")
    if stat.S_ISREG(info.st_mode):
        total_bytes += info.st_size
        if total_bytes > 250 * 1024 * 1024:
            raise SystemExit("evidence exceeds 250 MiB limit")
        files.append((path, relative, info.st_size))

if not files:
    raise SystemExit("audit did not create any evidence files")

for path, relative, size in files:
    lower = relative.name.lower()
    if lower.endswith((".tar.gz", ".tgz")):
        with tarfile.open(path, "r:gz") as archive:
            scanned = 0
            for member in archive.getmembers():
                member_path = pathlib.PurePosixPath(member.name)
                if member_path.is_absolute() or ".." in member_path.parts:
                    raise SystemExit(f"unsafe archive path: {member.name}")
                if member.issym() or member.islnk() or member.ischr() or member.isblk() or member.isfifo():
                    raise SystemExit(f"unsafe archive member type: {member.name}")
                if sensitive_name.search(member_path.as_posix()):
                    raise SystemExit(f"sensitive archive filename rejected: {member.name}")
                if member.isfile() and member.size <= 4 * 1024 * 1024 and scanned <= 32 * 1024 * 1024:
                    extracted = archive.extractfile(member)
                    if extracted is not None:
                        data = extracted.read()
                        scanned += len(data)
                        if sensitive_content.search(data):
                            raise SystemExit(f"sensitive archive content rejected: {member.name}")
    elif size <= 8 * 1024 * 1024:
        data = path.read_bytes()
        if sensitive_content.search(data):
            raise SystemExit(f"sensitive evidence content rejected: {relative}")

destination.mkdir(mode=0o700, parents=False, exist_ok=False)
manifest = []
for path, relative, size in files:
    target = destination / relative
    target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    shutil.copy2(path, target, follow_symlinks=False)
    os.chmod(target, 0o600)
    manifest.append(
        {
            "path": relative.as_posix(),
            "bytes": size,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        }
    )

(destination / "dispatcher-evidence-manifest.json").write_text(
    json.dumps(
        {
            "audit": audit,
            "audit_exit_code": audit_rc,
            "commit_sha": commit_sha,
            "files": manifest,
            "production_apply_authorized": False,
            "sanitization_passed": True,
            "total_bytes": total_bytes,
        },
        indent=2,
        sort_keys=True,
    )
    + "\n",
    encoding="utf-8",
)
os.chmod(destination / "dispatcher-evidence-manifest.json", 0o600)
PY

chown -R github-runner:github-runner "$EXPORT_DIR/audit-evidence"
printf '%s\n' "$AUDIT_RC" > "$EXPORT_DIR/audit-evidence/audit-exit-code.txt"
chown github-runner:github-runner "$EXPORT_DIR/audit-evidence/audit-exit-code.txt"
chmod 600 "$EXPORT_DIR/audit-evidence/audit-exit-code.txt"

printf 'AUDIT=%s\nREGISTERED_COMMIT=%s\nAUDIT_EXIT_CODE=%s\nPRODUCTION_APPLY_AUTHORIZED=false\n' \
  "$AUDIT" "$EXPECTED_SHA" "$AUDIT_RC"
exit "$AUDIT_RC"
DISPATCH

cat > "$TMPDIR_INSTALL/hermes-deals-audit-register" <<'REGISTER'
#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
umask 077
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PATH

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

[[ ${EUID:-$(id -u)} -eq 0 ]] || fail "register tool must run as root"
[[ $# -eq 3 ]] || fail "usage: hermes-deals-audit-register <audit> <commit-sha> <clean-main-repo>"

AUDIT="$1"
EXPECTED_SHA="$2"
REPO="$3"
REGISTRY_DIR='/etc/hermes-deals-audits.d'
LIBEXEC_DIR='/usr/local/libexec/hermes-deals-audits'

[[ "$EXPECTED_SHA" =~ ^[0-9a-f]{40}$ ]] || fail "invalid commit SHA"
case "$AUDIT" in
  b15m2-v08)
    RELATIVE_SCRIPT='tools/run-hermes-deals-b15m2-least-privilege-shadow-migration-api-regression-v08.sh'
    ;;
  *)
    fail "audit is not registerable: $AUDIT"
    ;;
esac

REPO="$(readlink -f -- "$REPO")"
[[ "$REPO" == '/home/andris/hermes-deals' ]] || fail "registration source must be /home/andris/hermes-deals"
[[ -d "$REPO/.git" ]] || fail "registration source is not a Git checkout"
[[ "$(git -C "$REPO" branch --show-current)" == 'main' ]] || fail "registration source branch must be main"
[[ "$(git -C "$REPO" rev-parse HEAD)" == "$EXPECTED_SHA" ]] || fail "registration source HEAD mismatch"
[[ -z "$(git -C "$REPO" status --porcelain)" ]] || fail "registration source worktree is not clean"

REMOTE="$(git -C "$REPO" remote get-url origin)"
case "$REMOTE" in
  https://github.com/rozkalnsandris/hermes-deals|https://github.com/rozkalnsandris/hermes-deals.git|git@github.com:rozkalnsandris/hermes-deals.git)
    ;;
  *)
    fail "registration source origin is not the Hermes Deals repository"
    ;;
esac

SOURCE_SCRIPT="$REPO/$RELATIVE_SCRIPT"
[[ -f "$SOURCE_SCRIPT" && ! -L "$SOURCE_SCRIPT" ]] || fail "approved audit script is missing or unsafe"
git -C "$REPO" ls-files --error-unmatch "$RELATIVE_SCRIPT" >/dev/null || fail "approved audit script is not tracked"

install -d -o root -g root -m 0755 "$LIBEXEC_DIR"
install -d -o root -g root -m 0755 "$REGISTRY_DIR"
INSTALLED_SCRIPT="$LIBEXEC_DIR/$AUDIT.sh"
install -o root -g root -m 0755 "$SOURCE_SCRIPT" "$INSTALLED_SCRIPT"
SCRIPT_SHA="$(sha256sum "$INSTALLED_SCRIPT" | awk '{print $1}')"

CONF_TMP="$(mktemp "$REGISTRY_DIR/.${AUDIT}.conf.XXXXXX")"
cleanup() {
  rm -f -- "$CONF_TMP"
}
trap cleanup EXIT
cat > "$CONF_TMP" <<EOF
audit_name='$AUDIT'
commit_sha='$EXPECTED_SHA'
script_sha256='$SCRIPT_SHA'
script_path='$INSTALLED_SCRIPT'
EOF
chown root:root "$CONF_TMP"
chmod 0644 "$CONF_TMP"
mv -f -- "$CONF_TMP" "$REGISTRY_DIR/$AUDIT.conf"
trap - EXIT

printf 'REGISTERED_AUDIT=%s\nCOMMIT_SHA=%s\nSCRIPT_SHA256=%s\nSCRIPT_PATH=%s\nPRODUCTION_APPLY_AUTHORIZED=false\n' \
  "$AUDIT" "$EXPECTED_SHA" "$SCRIPT_SHA" "$INSTALLED_SCRIPT"
REGISTER

cat > "$TMPDIR_INSTALL/hermes-deals-audit-runner.sudoers" <<'SUDOERS'
Defaults!/usr/local/sbin/hermes-deals-audit-dispatch env_reset,secure_path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
github-runner ALL=(root) NOPASSWD: /usr/local/sbin/hermes-deals-audit-dispatch
SUDOERS

chmod 0755 "$TMPDIR_INSTALL/hermes-deals-audit-dispatch" "$TMPDIR_INSTALL/hermes-deals-audit-register"
chmod 0440 "$TMPDIR_INSTALL/hermes-deals-audit-runner.sudoers"
visudo -cf "$TMPDIR_INSTALL/hermes-deals-audit-runner.sudoers" >/dev/null

install -d -o root -g root -m 0755 "$REGISTRY_DIR" "$LIBEXEC_DIR"
install -d -o andris -g andris -m 0700 "$STAGING_ROOT"
install -o root -g root -m 0755 "$TMPDIR_INSTALL/hermes-deals-audit-dispatch" "$DISPATCHER"
install -o root -g root -m 0755 "$TMPDIR_INSTALL/hermes-deals-audit-register" "$REGISTER"
install -o root -g root -m 0440 "$TMPDIR_INSTALL/hermes-deals-audit-runner.sudoers" "$SUDOERS"
visudo -cf "$SUDOERS" >/dev/null

systemctl is-active --quiet "$RUNNER_SERVICE" || {
  echo "ERROR: GitHub Actions runner service is not active: $RUNNER_SERVICE" >&2
  exit 1
}

sudo -l -U github-runner | grep -Fq '/usr/local/sbin/hermes-deals-audit-dispatch' || {
  echo "ERROR: github-runner dispatcher sudo rule was not installed" >&2
  exit 1
}

printf 'INSTALL_RESULT=PASS\nRUNNER_SERVICE=%s\nDISPATCHER_SHA256=%s\nREGISTER_SHA256=%s\nSUDOERS_VALID=true\nRUNNER_HAS_DOCKER_GROUP=%s\n' \
  "$RUNNER_SERVICE" \
  "$(sha256sum "$DISPATCHER" | awk '{print $1}')" \
  "$(sha256sum "$REGISTER" | awk '{print $1}')" \
  "$(id -nG github-runner | tr ' ' '\n' | grep -Fxq docker && echo true || echo false)"
