services:
  api:
    environment:
      HERMES_UI_ASSET_MODE: ${HERMES_UI_ASSET_MODE:?set_HERMES_UI_ASSET_MODE}
  web:
    volumes:
      - ${W4C_NGINX_CONFIG:?set_W4C_NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro
